#!/usr/bin/env bash
# Idempotent Cloud Agent setup for the Little Graduates PHP/MySQL app.
# Safe to run repeatedly: installs system packages, initialises the local
# MySQL database (schema + seeds + migrations), writes a local config, and
# seeds a demo admin so the app is immediately usable.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DB_NAME="lg_dev"
DB_USER="lg_dev"
DB_PASS="lg_dev_pass"
DB_HOST="127.0.0.1"

echo "==> Installing system packages (PHP, extensions, MySQL)…"
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends \
  php-cli php-mysql php-mbstring php-gd php-curl php-xml php-zip php-intl \
  mysql-server mysql-client

echo "==> Ensuring MySQL server is running…"
sudo service mysql start || true
# Wait for the server to accept connections.
for i in $(seq 1 30); do
  if sudo mysqladmin ping >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Creating database and application user (idempotent)…"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

echo "==> Writing includes/config.php (only if missing)…"
if [ ! -f includes/config.php ]; then
  cat > includes/config.php <<PHP
<?php
// Local development config for the Cloud Agent environment.
// Generated by .cursor/install.sh. Gitignored — never commit real credentials.

return [
    'db' => [
        'host'     => '${DB_HOST}',
        'name'     => '${DB_NAME}',
        'user'     => '${DB_USER}',
        'password' => '${DB_PASS}',
        'charset'  => 'utf8mb4',
    ],
    'app' => [
        'name'           => 'Little Graduates',
        'short_name'     => 'LG',
        'session_name'   => 'LG_SESSION',
        'max_pin_tries'  => 5,
        'lock_seconds'   => 30,
        'timezone'       => 'Asia/Kolkata',
    ],
];
PHP
fi

MYSQL="mysql -u${DB_USER} -p${DB_PASS} -h${DB_HOST} ${DB_NAME}"

echo "==> Applying base schema + seeds if the database is empty…"
HAS_USERS="$(${MYSQL} -N -B -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}' AND table_name='users';" 2>/dev/null || echo 0)"
if [ "${HAS_USERS}" = "0" ]; then
  echo "   -> fresh database: importing sql/schema.sql + sql/seeds.sql"
  ${MYSQL} < sql/schema.sql
  ${MYSQL} < sql/seeds.sql
else
  echo "   -> users table already present: skipping destructive schema import"
fi

echo "==> Applying migrations (idempotent)…"
php migrate.php

echo "==> Seeding a demo admin (PIN 1234) if no users exist…"
php -r '
$c = (require "includes/config.php")["db"];
$pdo = new PDO("mysql:host={$c["host"]};dbname={$c["name"]};charset=utf8mb4", $c["user"], $c["password"], [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
if ((int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn() === 0) {
  $pdo->prepare("INSERT INTO users (name, pin_hash, role, modules, active) VALUES (:n,:h,\"admin\",:m,1)")
      ->execute([":n"=>"Demo Admin", ":h"=>password_hash("1234", PASSWORD_DEFAULT), ":m"=>"tasks,montessori,students,crm,recruitment,staff,expenses,fees,logbook,inventory,wacrm,n8n"]);
  echo "   -> demo admin created (name: Demo Admin, PIN: 1234)\n";
} else {
  echo "   -> users already exist, leaving them untouched\n";
}
'

echo "==> Install complete."
